version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest-lite
    ports:
      - '8098:8080'
    volumes:
      #      - /location/of/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - ${vols}/stirl:/configs
    environment:
      APP_LOCALE: en_US
      APP_HOME_NAME: Stirling PDF
      APP_HOME_DESCRIPTION: Your locally hosted one-stop-shop for all your PDF needs.
      APP_NAVBAR_NAME: Stirling PDF
        #      APP_ROOT_PATH:
#      ALLOW_GOOGLE_VISIBILITY: true

