version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "127.0.0.1:8880:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://sapi.systuner.com # This MUST be included as a valid URL in the spotify dashboard (see below)
      - CLIENT_ENDPOINT=https://music.systuner.com
        #- SPOTIFY_PUBLIC=
        #- SPOTIFY_SECRET=
      - CORS=all # all if you want to allow every origin
    env_file:
      - secrets.env
  mongo:
    restart: always
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ${vols}/your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "127.0.0.1:3030:3000"
    environment:
      - API_ENDPOINT=https://sapi.systuner.com
