version: '3.5'


services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    # Binds to 8096
    network_mode: 'host'
    volumes:
      - ${vols}/jellyfin/config:/config
      - ${vols}/jellyfin/cache:/cache
      - ${vols}/jellyfin/media:/media
      - ${vols}/jellyfin/media2:/media2:ro
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://media.systuner.com
