version: '3'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '127.0.0.1:81:81'
      - '443:443'
    volumes:
      - ${vols}/nginx-pm/data:/data
      - ${vols}/nginx-pm/letsencrypt:/etc/letsencrypt
    # This is added so that we can see host ports and other
    # containers which are bound to the host, typically this
    # container would need to be on the same network as the others
    # to be able to reverse proxy shit
    network_mode: host
        # extra_hosts:
        #- "host.docker.internal:host-gateway"
